from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStorage(Protocol):
    name: str

    def put(self, bucket: str, key: str, data: bytes, *, content_type: str = "application/octet-stream") -> str: ...
    def get(self, bucket: str, key: str) -> bytes: ...
    def exists(self, bucket: str, key: str) -> bool: ...
    def uri(self, bucket: str, key: str) -> str: ...
    # #36: 객체 열거·삭제를 인터페이스에 추가 — 보존정책·재처리·암호화 마이그레이션이
    # 백엔드 client를 직접 까지 않고 추상화만으로 돌도록(추상화 누수 제거).
    def list_keys(self, bucket: str, prefix: str = "") -> list[str]: ...
    def delete(self, bucket: str, key: str) -> None: ...
