"""Check if an alembic autogenerated revision is empty (no drift).

Returns exit code 0 if upgrade()/downgrade() bodies are effectively empty
(only `pass` and/or a docstring), 1 if they contain any operations.

Used by P3 migration-drift CI step as the fallback path when
`alembic check` is unavailable or inconclusive.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path


def _is_effectively_pass(body: list[ast.stmt]) -> bool:
    """Body is empty if it's only `pass` and/or a string docstring expression."""
    meaningful = [
        n
        for n in body
        if not (
            isinstance(n, ast.Expr)
            and isinstance(n.value, ast.Constant)
            and isinstance(n.value.value, str)
        )
        and not isinstance(n, ast.Pass)
    ]
    return len(meaningful) == 0


def main(path: str) -> int:
    src = Path(path).read_text(encoding="utf-8")
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name in ("upgrade", "downgrade"):
            if not _is_effectively_pass(node.body):
                return 1
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <revision_file.py>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
