"""Build a deterministic, self-verifying proxy runtime source release.

The release is intentionally code-and-policy only.  Raw corpora, generated
records, secrets, model outputs, and the sealed public-v2 holdout never enter
the allowlist.  Publication succeeds only after a clean extraction can import
and execute ``--help`` for every required entry point.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import gzip
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import subprocess
import sys
import tarfile
import tempfile
from typing import Mapping, Sequence


_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent

SCHEMA = "proxy-runtime-release-v1"
ARCHIVE_ROOT = "proxy-runtime"
DEFAULT_SOURCE_DATE_EPOCH = 0
MAX_SOURCE_DATE_EPOCH = (1 << 32) - 1
MAX_FILE_BYTES = 8 * 1024 * 1024
MAX_PAYLOAD_BYTES = 32 * 1024 * 1024

# Exact files are deliberately boring: no generated JSONL, model output,
# collection run, report, credential, or evaluation artifact can be pulled in
# by a broad repository glob.
ALLOWLIST_FILES = (
    "README.md",
    "docs/KL_PROXY_GOLD_RUNBOOK.md",
    "docs/LEGACY_RAW_MODEL_PROVENANCE.md",
    "pyproject.toml",
    "uv.lock",
    "scripts/build_proxy_runtime_release.py",
    "scripts/build_proxy_scenarios.py",
    "scripts/run_proxy_generation_shards.py",
    "scripts/judge_proxy_candidates.py",
    "scripts/run_proxy_judging_shards.py",
    "scripts/assemble_proxy_gold.py",
    "scripts/assemble_public_s3_challenge.py",
    "scripts/assemble_public_s3_training_pool.py",
    "scripts/assemble_proxy_training_pool.py",
    "scripts/validate_proxy_corpus.py",
    "scripts/materialize_proxy_training_set.py",
    "scripts/finalize_proxy_classifier.py",
    "scripts/attest_legacy_training_corpus.py",
    "scripts/compare_proxy_models.py",
    "scripts/evaluate_public_s3_challenge.py",
    "scripts/p1_train_classifier.py",
    "scripts/intake_aihub_71813.py",
    "scripts/collect_korea_policy_pages.py",
    "datasets/proxy_gold/scenario_catalog.v1.json",
    "datasets/proxy_gold/training_scenario_catalog.v1.json",
    "datasets/proxy_gold/public_source_registry.v1.json",
    "datasets/proxy_gold/PUBLIC_REAL_TRAINING_POLICY.md",
    "datasets/proxy_gold/AIHUB_71813_INTAKE.md",
    "datasets/proxy_gold/aihub_71813_approval_receipt.template.json",
    "deploy/proxy_gold_runtime/compose.yaml",
    "deploy/proxy_gold_runtime/model-lock.json",
    "deploy/proxy_gold_runtime/prefetch_models.sh",
    "deploy/proxy_gold_runtime/README.md",
)

# Python-only recursive trees.  The suffix restriction is part of the
# allowlist, so static samples, models, caches, and arbitrary data cannot enter.
ALLOWLIST_PYTHON_TREES = ("src/koipa",)

# The source tree intentionally has no scripts/__init__.py.  A runtime archive
# adds one deterministic marker so an unrelated site-packages ``scripts``
# package cannot capture ``python -m scripts.<entrypoint>``.
GENERATED_FILES: Mapping[str, bytes] = {
    "scripts/__init__.py": (
        b'"""Proxy runtime command package (generated by the release builder)."""\n'
    )
}

REQUIRED_ENTRYPOINTS = (
    "scripts.build_proxy_scenarios",
    "scripts.run_proxy_generation_shards",
    "scripts.judge_proxy_candidates",
    "scripts.run_proxy_judging_shards",
    "scripts.assemble_proxy_gold",
    "scripts.assemble_public_s3_challenge",
    "scripts.assemble_public_s3_training_pool",
    "scripts.assemble_proxy_training_pool",
    "scripts.validate_proxy_corpus",
    "scripts.materialize_proxy_training_set",
    "scripts.finalize_proxy_classifier",
    "scripts.attest_legacy_training_corpus",
    "scripts.compare_proxy_models",
    "scripts.evaluate_public_s3_challenge",
    "scripts.p1_train_classifier",
    "scripts.intake_aihub_71813",
    "scripts.collect_korea_policy_pages",
)

_BLOCKED_COMPONENTS = frozenset(
    {
        ".git",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        "secrets",
        "secret",
        "credentials",
        "raw",
        "raw_html",
        "korea_policy_runs",
        "public_s3_challenges",
        "public_s3_training",
        "golden_runs",
        "training_runs",
        "reports",
        "artifacts",
        "_artifacts",
    }
)
_BLOCKED_SUFFIXES = frozenset(
    {
        ".pyc",
        ".pyo",
        ".pem",
        ".key",
        ".p12",
        ".pfx",
        ".jsonl",
        ".tar",
        ".gz",
        ".zip",
    }
)
_BLOCKED_FILE_NAMES = frozenset(
    {
        ".env",
        "id_rsa",
        "id_ed25519",
        "credentials.json",
        "secrets.json",
    }
)
_BLOCKED_PATH_MARKERS = (
    "public-s3-300-blind",
    "sealed-v2",
    "sealed_v2",
)
_PRIVATE_KEY_MARKERS = tuple(
    ("-----BEGIN " + kind + "-----").encode("ascii")
    for kind in (
        "PRIVATE KEY",
        "RSA PRIVATE KEY",
        "OPENSSH PRIVATE KEY",
        "EC PRIVATE KEY",
    )
)


class ProxyRuntimeReleaseError(ValueError):
    """The runtime archive cannot be published without weakening its contract."""


@dataclass(frozen=True)
class ReleaseFile:
    path: str
    payload: bytes
    sha256: str


@dataclass(frozen=True)
class ReleaseBuild:
    output_path: Path
    archive_sha256: str
    content_sha256: str
    manifest_sha256: str
    file_count: int


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _canonical_json_bytes(value: object) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        + b"\n"
    )


def _relative_posix(source_root: Path, path: Path) -> str:
    try:
        relative = path.resolve().relative_to(source_root.resolve())
    except ValueError as exc:
        raise ProxyRuntimeReleaseError(
            f"allowlisted path escapes source root: {path}"
        ) from exc
    value = relative.as_posix()
    if not value or value.startswith("../"):
        raise ProxyRuntimeReleaseError(f"invalid release path: {path}")
    return value


def _assert_safe_release_path(relative: str) -> None:
    if (
        not isinstance(relative, str)
        or not relative
        or "\\" in relative
        or "\x00" in relative
    ):
        raise ProxyRuntimeReleaseError(f"prohibited release path: {relative!r}")
    path = PurePosixPath(relative)
    lowered_parts = tuple(part.casefold() for part in path.parts)
    lowered = relative.casefold()
    if (
        relative == "."
        or path.as_posix() != relative
        or path.is_absolute()
        or ".." in path.parts
        or any(part in _BLOCKED_COMPONENTS for part in lowered_parts)
        or path.suffix.casefold() in _BLOCKED_SUFFIXES
        or path.name.casefold() in _BLOCKED_FILE_NAMES
        or path.name.casefold().startswith(".env.")
        or any(marker in lowered for marker in _BLOCKED_PATH_MARKERS)
    ):
        raise ProxyRuntimeReleaseError(f"prohibited release path: {relative}")


def _is_explicitly_allowlisted(
    relative: str,
    *,
    allowlist_files: Sequence[str],
    python_trees: Sequence[str],
    generated_files: Mapping[str, bytes],
) -> bool:
    normalized = PurePosixPath(relative).as_posix()
    exact = {
        PurePosixPath(value).as_posix()
        for value in (*allowlist_files, *generated_files.keys())
    }
    if normalized in exact:
        return True
    path = PurePosixPath(normalized)
    return path.suffix == ".py" and any(
        path.is_relative_to(PurePosixPath(tree)) for tree in python_trees
    )


def _read_release_file(source_root: Path, path: Path) -> ReleaseFile:
    if path.is_symlink() or not path.is_file():
        raise ProxyRuntimeReleaseError(
            f"allowlisted release file is missing, irregular, or a symlink: {path}"
        )
    relative = _relative_posix(source_root, path)
    _assert_safe_release_path(relative)
    try:
        payload = path.read_bytes()
    except OSError as exc:
        raise ProxyRuntimeReleaseError(
            f"cannot read release file {path}: {exc}"
        ) from exc
    if len(payload) > MAX_FILE_BYTES:
        raise ProxyRuntimeReleaseError(
            f"allowlisted file exceeds {MAX_FILE_BYTES} bytes: {relative}"
        )
    if any(marker in payload for marker in _PRIVATE_KEY_MARKERS):
        raise ProxyRuntimeReleaseError(
            f"private-key material detected in allowlisted file: {relative}"
        )
    return ReleaseFile(relative, payload, _sha256(payload))


def collect_release_files(
    source_root: Path,
    *,
    allowlist_files: Sequence[str] = ALLOWLIST_FILES,
    python_trees: Sequence[str] = ALLOWLIST_PYTHON_TREES,
    generated_files: Mapping[str, bytes] = GENERATED_FILES,
) -> tuple[ReleaseFile, ...]:
    """Resolve the explicit allowlist and reject every unsafe path or payload."""
    root = source_root.resolve()
    if source_root.is_symlink() or not root.is_dir():
        raise ProxyRuntimeReleaseError(
            f"source root must be a regular directory: {source_root}"
        )
    paths: list[Path] = []
    for relative in allowlist_files:
        _assert_safe_release_path(PurePosixPath(relative).as_posix())
        paths.append(root / Path(relative))
    for relative in python_trees:
        tree = root / Path(relative)
        _assert_safe_release_path(PurePosixPath(relative).as_posix())
        if tree.is_symlink() or not tree.is_dir():
            raise ProxyRuntimeReleaseError(
                f"allowlisted Python tree is missing or irregular: {tree}"
            )
        paths.extend(
            path
            for path in tree.rglob("*.py")
            if path.is_file() and not path.is_symlink()
        )

    resolved: dict[str, ReleaseFile] = {}
    for path in paths:
        item = _read_release_file(root, path)
        if item.path in resolved:
            raise ProxyRuntimeReleaseError(
                f"duplicate release allowlist path: {item.path}"
            )
        resolved[item.path] = item
    for relative, payload in generated_files.items():
        normalized = PurePosixPath(relative).as_posix()
        _assert_safe_release_path(normalized)
        if normalized in resolved:
            raise ProxyRuntimeReleaseError(
                f"generated release path collides with source: {normalized}"
            )
        if not isinstance(payload, bytes):
            raise ProxyRuntimeReleaseError(
                f"generated release payload must be bytes: {normalized}"
            )
        resolved[normalized] = ReleaseFile(normalized, payload, _sha256(payload))
    if not resolved:
        raise ProxyRuntimeReleaseError("release allowlist resolved to no files")
    total = sum(len(item.payload) for item in resolved.values())
    if total > MAX_PAYLOAD_BYTES:
        raise ProxyRuntimeReleaseError(
            f"release payload exceeds {MAX_PAYLOAD_BYTES} bytes: {total}"
        )
    return tuple(resolved[path] for path in sorted(resolved))


def _content_descriptor(files: Sequence[ReleaseFile]) -> list[dict[str, object]]:
    return [
        {"path": item.path, "bytes": len(item.payload), "sha256": item.sha256}
        for item in files
    ]


def _release_manifest(
    files: Sequence[ReleaseFile],
    *,
    source_date_epoch: int,
    required_entrypoints: Sequence[str],
) -> dict[str, object]:
    descriptor = _content_descriptor(files)
    content_sha256 = _sha256(_canonical_json_bytes(descriptor))
    return {
        "schema": SCHEMA,
        "archive_root": ARCHIVE_ROOT,
        "source_date_epoch": source_date_epoch,
        "reproducible_metadata": {
            "uid": 0,
            "gid": 0,
            "uname": "",
            "gname": "",
            "file_mode": "0644",
            "directory_mode": "0755",
            "gzip_filename": "",
        },
        "content_hash": {
            "algorithm": "sha256(canonical-json(file path,bytes,sha256))",
            "sha256": content_sha256,
        },
        "files": descriptor,
        "required_entrypoints": list(required_entrypoints),
        "closure_checks": ["import", "--help"],
        "exclusion_contract": {
            "allowlist_only": True,
            "python_tree_suffix": ".py",
            "excluded": [
                "__pycache__ and bytecode",
                "secret/credential/private-key paths and private-key payloads",
                "raw corpora and generated JSONL",
                "collection/training runs and reports",
                "public S3 challenge artifacts including sealed v2",
                "model artifacts and archives",
            ],
        },
    }


def _tar_info(name: str, payload: bytes, *, source_date_epoch: int) -> tarfile.TarInfo:
    info = tarfile.TarInfo(name=name)
    info.size = len(payload)
    info.mtime = source_date_epoch
    info.mode = 0o644
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    info.type = tarfile.REGTYPE
    info.pax_headers = {}
    return info


def _archive_bytes(
    files: Sequence[ReleaseFile],
    manifest_payload: bytes,
    *,
    source_date_epoch: int,
) -> bytes:
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="",
        mode="wb",
        fileobj=compressed,
        mtime=source_date_epoch,
        compresslevel=9,
    ) as gzip_stream:
        with tarfile.open(
            fileobj=gzip_stream,
            mode="w",
            format=tarfile.PAX_FORMAT,
        ) as archive:
            payloads = {
                **{item.path: item.payload for item in files},
                "RELEASE_MANIFEST.json": manifest_payload,
            }
            for relative in sorted(payloads):
                payload = payloads[relative]
                name = f"{ARCHIVE_ROOT}/{relative}"
                archive.addfile(
                    _tar_info(name, payload, source_date_epoch=source_date_epoch),
                    io.BytesIO(payload),
                )
    return compressed.getvalue()


def _safe_extract_archive(archive_path: Path, destination: Path) -> Path:
    root = destination.resolve()
    try:
        archive = tarfile.open(archive_path, mode="r:gz")
    except (OSError, tarfile.TarError) as exc:
        raise ProxyRuntimeReleaseError(f"cannot open runtime release: {exc}") from exc
    with archive:
        members = archive.getmembers()
        names = [member.name for member in members]
        if names != sorted(names) or len(names) != len(set(names)):
            raise ProxyRuntimeReleaseError(
                "runtime release members are unsorted or duplicated"
            )
        total_bytes = 0
        for member in members:
            if not member.isfile() or member.issym() or member.islnk():
                raise ProxyRuntimeReleaseError(
                    f"runtime release contains a non-regular member: {member.name}"
                )
            pure = PurePosixPath(member.name)
            if (
                pure.is_absolute()
                or ".." in pure.parts
                or len(pure.parts) < 2
                or pure.parts[0] != ARCHIVE_ROOT
            ):
                raise ProxyRuntimeReleaseError(
                    f"runtime release contains an unsafe member: {member.name}"
                )
            relative = PurePosixPath(*pure.parts[1:]).as_posix()
            if relative != "RELEASE_MANIFEST.json":
                _assert_safe_release_path(relative)
            total_bytes += member.size
            if member.size > MAX_FILE_BYTES or total_bytes > MAX_PAYLOAD_BYTES:
                raise ProxyRuntimeReleaseError(
                    f"runtime release exceeds payload limits: {member.name}"
                )
            target = (root / Path(*pure.parts)).resolve()
            if root not in target.parents:
                raise ProxyRuntimeReleaseError(
                    f"runtime release member escapes extraction root: {member.name}"
                )
            handle = archive.extractfile(member)
            if handle is None:
                raise ProxyRuntimeReleaseError(
                    f"cannot read runtime release member: {member.name}"
                )
            payload = handle.read()
            if len(payload) != member.size:
                raise ProxyRuntimeReleaseError(
                    f"truncated runtime release member: {member.name}"
                )
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
    extracted = root / ARCHIVE_ROOT
    if not extracted.is_dir():
        raise ProxyRuntimeReleaseError("runtime release has no canonical root")
    return extracted


_CLOSURE_PROGRAM = r"""
import importlib
from pathlib import Path
import runpy
import sys

root = Path(sys.argv[1]).resolve()
source = Path(sys.argv[2]).resolve()
module_name = sys.argv[3]
mode = sys.argv[4]
sys.path[:0] = [str(root / "src"), str(root)]

if mode == "import":
    importlib.import_module(module_name)
elif mode == "help":
    sys.argv = [module_name, "--help"]
    try:
        runpy.run_module(module_name, run_name="__main__")
    except SystemExit as exc:
        if exc.code not in (None, 0):
            raise
else:
    raise RuntimeError(mode)

# 인터프리터 환경(venv)은 '소스 워크트리'가 아니다. 표준 설치가 poc/.venv 라
# (README 빠른시작: python -m venv .venv) venv 가 source 아래에 들어오고, 그러면 설치된
# 서드파티가 전부 source-worktree fallback 으로 오판된다. 실제로 setuptools 가 .pth 로
# 자동 로드하는 _distutils_hack 이 항상 걸려 이 검사가 상시 실패했다.
# 검사 의도(릴리스가 프로젝트 '소스'로 되돌아가지 않는가)는 그대로 두고 환경만 뺀다.
env_roots = [Path(sys.prefix).resolve()]
if sys.base_prefix != sys.prefix:
    env_roots.append(Path(sys.base_prefix).resolve())


def _under(path, base):
    return path == base or base in path.parents


for name, module in list(sys.modules.items()):
    origins = []
    file_name = getattr(module, "__file__", None)
    if file_name:
        origins.append(Path(file_name).resolve())
    module_paths = getattr(module, "__path__", None)
    if module_paths:
        origins.extend(Path(value).resolve() for value in module_paths)
    for origin in origins:
        if any(_under(origin, base) for base in env_roots):
            continue
        local_name = name == "koipa" or name.startswith("koipa.")
        local_name = local_name or name == "scripts" or name.startswith("scripts.")
        under_root = _under(origin, root)
        under_source = _under(origin, source)
        if local_name and not under_root:
            raise RuntimeError(f"local module escaped release: {name} -> {origin}")
        if under_source and not under_root:
            raise RuntimeError(f"source-worktree fallback detected: {name} -> {origin}")
"""


def _run_closure_checks(
    extracted_root: Path,
    *,
    source_root: Path,
    required_entrypoints: Sequence[str],
) -> None:
    environment = dict(os.environ)
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    for module in required_entrypoints:
        expected_path = extracted_root / Path(*module.split(".")).with_suffix(".py")
        if not expected_path.is_file():
            raise ProxyRuntimeReleaseError(
                f"required entrypoint is absent from release: {module}"
            )
        for mode in ("import", "help"):
            try:
                completed = subprocess.run(
                    [
                        sys.executable,
                        "-I",
                        "-B",
                        "-c",
                        _CLOSURE_PROGRAM,
                        str(extracted_root),
                        str(source_root.resolve()),
                        module,
                        mode,
                    ],
                    cwd=extracted_root,
                    env=environment,
                    capture_output=True,
                    text=True,
                    timeout=45,
                    check=False,
                )
            except (OSError, subprocess.TimeoutExpired) as exc:
                raise ProxyRuntimeReleaseError(
                    f"entrypoint {mode} closure could not run for {module}: {exc}"
                ) from exc
            if completed.returncode != 0:
                detail = (completed.stderr or completed.stdout)[-4000:]
                raise ProxyRuntimeReleaseError(
                    f"entrypoint {mode} closure failed for {module}: {detail.strip()}"
                )


def verify_release_archive(
    archive_path: Path,
    *,
    source_root: Path = _PROJECT_ROOT,
    required_entrypoints: Sequence[str] = REQUIRED_ENTRYPOINTS,
    allowlist_files: Sequence[str] = ALLOWLIST_FILES,
    python_trees: Sequence[str] = ALLOWLIST_PYTHON_TREES,
    generated_files: Mapping[str, bytes] = GENERATED_FILES,
) -> dict[str, object]:
    """Verify exact content and clean-extraction entrypoint closure."""
    if archive_path.is_symlink() or not archive_path.is_file():
        raise ProxyRuntimeReleaseError(
            f"runtime release must be a regular archive: {archive_path}"
        )
    with tempfile.TemporaryDirectory(prefix="proxy-runtime-verify-") as temporary:
        extracted_root = _safe_extract_archive(archive_path, Path(temporary))
        manifest_path = extracted_root / "RELEASE_MANIFEST.json"
        try:
            manifest_payload = manifest_path.read_bytes()
            manifest = json.loads(manifest_payload.decode("utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as exc:
            raise ProxyRuntimeReleaseError(
                f"invalid runtime release manifest: {exc}"
            ) from exc
        if (
            not isinstance(manifest, dict)
            or manifest.get("schema") != SCHEMA
            or manifest.get("archive_root") != ARCHIVE_ROOT
            or manifest.get("required_entrypoints") != list(required_entrypoints)
            or manifest.get("closure_checks") != ["import", "--help"]
            or manifest.get("reproducible_metadata")
            != {
                "uid": 0,
                "gid": 0,
                "uname": "",
                "gname": "",
                "file_mode": "0644",
                "directory_mode": "0755",
                "gzip_filename": "",
            }
            or manifest_payload != _canonical_json_bytes(manifest)
        ):
            raise ProxyRuntimeReleaseError("runtime release manifest contract mismatch")
        source_date_epoch = manifest.get("source_date_epoch")
        if (
            isinstance(source_date_epoch, bool)
            or not isinstance(source_date_epoch, int)
            or not 0 <= source_date_epoch <= MAX_SOURCE_DATE_EPOCH
        ):
            raise ProxyRuntimeReleaseError(
                "runtime release has invalid reproducible timestamp"
            )
        archive_payload = archive_path.read_bytes()
        if (
            len(archive_payload) < 10
            or archive_payload[:2] != b"\x1f\x8b"
            or int.from_bytes(archive_payload[4:8], "little") != source_date_epoch
            or archive_payload[2] != 8
            or archive_payload[3] != 0
            or archive_payload[8] != 2
            or archive_payload[9] != 255
        ):
            raise ProxyRuntimeReleaseError(
                "runtime release gzip metadata is not reproducible"
            )
        with tarfile.open(archive_path, mode="r:gz") as archive:
            for member in archive.getmembers():
                if (
                    member.mtime != source_date_epoch
                    or member.uid != 0
                    or member.gid != 0
                    or member.uname != ""
                    or member.gname != ""
                    or member.mode != 0o644
                ):
                    raise ProxyRuntimeReleaseError(
                        f"runtime release metadata mismatch: {member.name}"
                    )
        declared_files = manifest.get("files")
        if not isinstance(declared_files, list) or not declared_files:
            raise ProxyRuntimeReleaseError("runtime release manifest has no files")
        actual_paths = sorted(
            path.relative_to(extracted_root).as_posix()
            for path in extracted_root.rglob("*")
            if path.is_file() and path.name != "RELEASE_MANIFEST.json"
        )
        declared_paths: list[str] = []
        for index, item in enumerate(declared_files):
            if not isinstance(item, Mapping):
                raise ProxyRuntimeReleaseError(
                    f"invalid runtime release file attestation at index {index}"
                )
            if set(item) != {"path", "bytes", "sha256"}:
                raise ProxyRuntimeReleaseError(
                    f"invalid runtime release file attestation at index {index}"
                )
            relative_value = item.get("path")
            if not isinstance(relative_value, str):
                raise ProxyRuntimeReleaseError(
                    f"invalid runtime release file path at index {index}"
                )
            relative = relative_value
            _assert_safe_release_path(relative)
            if not _is_explicitly_allowlisted(
                relative,
                allowlist_files=allowlist_files,
                python_trees=python_trees,
                generated_files=generated_files,
            ):
                raise ProxyRuntimeReleaseError(
                    f"runtime release file is outside the explicit allowlist: {relative}"
                )
            if relative in declared_paths:
                raise ProxyRuntimeReleaseError(
                    f"duplicate runtime release file attestation: {relative}"
                )
            declared_paths.append(relative)
            path = extracted_root / Path(*PurePosixPath(relative).parts)
            if not path.is_file():
                raise ProxyRuntimeReleaseError(
                    f"declared runtime release file is missing: {relative}"
                )
            payload = path.read_bytes()
            if any(marker in payload for marker in _PRIVATE_KEY_MARKERS):
                raise ProxyRuntimeReleaseError(
                    f"private-key material detected in runtime release: {relative}"
                )
            declared_bytes = item.get("bytes")
            declared_sha256 = item.get("sha256")
            if (
                isinstance(declared_bytes, bool)
                or not isinstance(declared_bytes, int)
                or not isinstance(declared_sha256, str)
                or declared_bytes != len(payload)
                or declared_sha256 != _sha256(payload)
            ):
                raise ProxyRuntimeReleaseError(
                    f"runtime release file attestation mismatch: {relative}"
                )
            generated_payload = generated_files.get(relative)
            if generated_payload is not None and payload != generated_payload:
                raise ProxyRuntimeReleaseError(
                    f"generated runtime release payload mismatch: {relative}"
                )
        if declared_paths != actual_paths:
            raise ProxyRuntimeReleaseError(
                "runtime release contains undeclared or missing payload files"
            )
        descriptor = [dict(item) for item in declared_files]
        expected_content = _sha256(_canonical_json_bytes(descriptor))
        content_hash = manifest.get("content_hash")
        if (
            not isinstance(content_hash, Mapping)
            or content_hash.get("algorithm")
            != "sha256(canonical-json(file path,bytes,sha256))"
            or content_hash.get("sha256") != expected_content
        ):
            raise ProxyRuntimeReleaseError("runtime release content hash mismatch")
        if list(required_entrypoints):
            _run_closure_checks(
                extracted_root,
                source_root=source_root,
                required_entrypoints=required_entrypoints,
            )
        if list(extracted_root.rglob("__pycache__")) or list(
            extracted_root.rglob("*.pyc")
        ):
            raise ProxyRuntimeReleaseError(
                "closure verification created bytecode cache"
            )
        return {
            "schema": SCHEMA,
            "archive_sha256": _sha256(archive_path.read_bytes()),
            "manifest_sha256": _sha256(manifest_payload),
            "content_sha256": expected_content,
            "files": len(declared_files),
            "entrypoints": len(required_entrypoints),
        }


def _atomic_publish(path: Path, payload: bytes) -> None:
    if path.exists():
        raise ProxyRuntimeReleaseError(f"refusing to overwrite release: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            # The temporary lives in the destination directory, so a hard link
            # publishes the complete inode atomically and, unlike os.replace,
            # cannot overwrite a release won by another concurrent builder.
            os.link(temporary, path)
        except FileExistsError as exc:
            raise ProxyRuntimeReleaseError(
                f"refusing to overwrite release: {path}"
            ) from exc
    finally:
        temporary.unlink(missing_ok=True)


def build_runtime_release(
    source_root: Path,
    output_path: Path,
    *,
    source_date_epoch: int = DEFAULT_SOURCE_DATE_EPOCH,
    allowlist_files: Sequence[str] = ALLOWLIST_FILES,
    python_trees: Sequence[str] = ALLOWLIST_PYTHON_TREES,
    generated_files: Mapping[str, bytes] = GENERATED_FILES,
    required_entrypoints: Sequence[str] = REQUIRED_ENTRYPOINTS,
) -> ReleaseBuild:
    """Build, clean-extract, verify, then atomically publish one release."""
    if (
        isinstance(source_date_epoch, bool)
        or not isinstance(source_date_epoch, int)
        or not 0 <= source_date_epoch <= MAX_SOURCE_DATE_EPOCH
    ):
        raise ProxyRuntimeReleaseError(
            f"source_date_epoch must be between 0 and {MAX_SOURCE_DATE_EPOCH}"
        )
    if output_path.exists():
        raise ProxyRuntimeReleaseError(f"refusing to overwrite release: {output_path}")
    files = collect_release_files(
        source_root,
        allowlist_files=allowlist_files,
        python_trees=python_trees,
        generated_files=generated_files,
    )
    required_scripts = {
        f"{module.replace('.', '/')}.py" for module in required_entrypoints
    }
    missing_entrypoints = sorted(required_scripts - {item.path for item in files})
    if missing_entrypoints:
        raise ProxyRuntimeReleaseError(
            "required entrypoints are absent from the allowlist: "
            + ", ".join(missing_entrypoints)
        )
    manifest = _release_manifest(
        files,
        source_date_epoch=source_date_epoch,
        required_entrypoints=required_entrypoints,
    )
    manifest_payload = _canonical_json_bytes(manifest)
    archive_payload = _archive_bytes(
        files,
        manifest_payload,
        source_date_epoch=source_date_epoch,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix=f".{output_path.name}.verify-", dir=output_path.parent
    ) as temporary:
        candidate = Path(temporary) / output_path.name
        candidate.write_bytes(archive_payload)
        audit = verify_release_archive(
            candidate,
            source_root=source_root,
            required_entrypoints=required_entrypoints,
            allowlist_files=allowlist_files,
            python_trees=python_trees,
            generated_files=generated_files,
        )
    confirmed_files = collect_release_files(
        source_root,
        allowlist_files=allowlist_files,
        python_trees=python_trees,
        generated_files=generated_files,
    )
    if _content_descriptor(confirmed_files) != _content_descriptor(files):
        raise ProxyRuntimeReleaseError(
            "allowlisted source changed while the runtime release was being verified"
        )
    _atomic_publish(output_path, archive_payload)
    return ReleaseBuild(
        output_path=output_path.resolve(),
        archive_sha256=str(audit["archive_sha256"]),
        content_sha256=str(audit["content_sha256"]),
        manifest_sha256=str(audit["manifest_sha256"]),
        file_count=int(audit["files"]),
    )


def _source_date_epoch_default() -> int:
    raw = os.environ.get("SOURCE_DATE_EPOCH", str(DEFAULT_SOURCE_DATE_EPOCH))
    try:
        value = int(raw)
    except ValueError as exc:
        raise ProxyRuntimeReleaseError("SOURCE_DATE_EPOCH must be an integer") from exc
    if not 0 <= value <= MAX_SOURCE_DATE_EPOCH:
        raise ProxyRuntimeReleaseError(
            f"SOURCE_DATE_EPOCH must be between 0 and {MAX_SOURCE_DATE_EPOCH}"
        )
    return value


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=_PROJECT_ROOT)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("artifacts/proxy_runtime/proxy-runtime.tar.gz"),
    )
    parser.add_argument("--source-date-epoch", type=int)
    parser.add_argument(
        "--verify-only",
        type=Path,
        help="verify an existing runtime release without building a new archive",
    )
    args = parser.parse_args(argv)
    try:
        if args.verify_only is not None:
            audit = verify_release_archive(
                args.verify_only,
                source_root=args.source_root,
            )
            print(json.dumps({"ready": True, **audit}, sort_keys=True))
            return 0
        source_date_epoch = (
            _source_date_epoch_default()
            if args.source_date_epoch is None
            else args.source_date_epoch
        )
        result = build_runtime_release(
            args.source_root,
            args.out,
            source_date_epoch=source_date_epoch,
        )
    except ProxyRuntimeReleaseError as exc:
        print(
            json.dumps({"ready": False, "error": str(exc)}, ensure_ascii=False),
            file=sys.stderr,
        )
        return 2
    print(
        json.dumps(
            {
                "ready": True,
                "archive": str(result.output_path),
                "archive_sha256": result.archive_sha256,
                "content_sha256": result.content_sha256,
                "manifest_sha256": result.manifest_sha256,
                "files": result.file_count,
                "entrypoints": len(REQUIRED_ENTRYPOINTS),
            },
            ensure_ascii=False,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
