# -*- coding: utf-8 -*-
"""테이블정의서의 사람 서술 부분 — 논리명·용도·컬럼 설명.

스키마 사실(컬럼·타입·NULL·기본값·키·인덱스)은 여기 적지 않는다. 그것은
poc/src/koipa/db/models.py 와 alembic 마이그레이션에서 build_table_spec.py 가
직접 읽는다. 이 파일은 코드가 알려줄 수 없는 것 — 한국어 이름과 뜻 — 만 담는다.

컬럼을 추가하고 여기에 설명을 안 적으면 build_table_spec.py 가 미기술로 세어
경고한다. 문서가 코드보다 뒤처지는 것을 막는 장치다.
"""

# 그룹 구분은 models.py 모듈 docstring 의 도메인 구분과 같다.
GROUPS = [
    ("A", "등급체계", "영업비밀 등급 정의와 판정 요건·키워드 사전."),
    ("B", "문서", "업로드 원문 메타와 청킹 결과."),
    ("C", "라벨링", "문서별 확정 등급과 요건 점수."),
    ("D", "추론", "분류 결과와 그 판단 근거."),
    ("E", "학습", "모델 버전 레지스트리와 학습 실행 이력."),
    ("F", "보정", "검수자 확정·교정 결과. 운영 재학습의 진실 소스."),
    ("G", "합성", "학습용 합성 문서 생성 이력과 프롬프트 버전."),
    ("H", "운영", "비용·감사·가이드 이력."),
    ("I", "검색", "RAG 벡터스토어. Alembic SQL 로만 생성한다(ORM 매핑 없음)."),
]

TABLES = {
    "tb_classification_levels": ("A", "분류 등급", "영업비밀 등급(TS·S1·S2·S3) 정의. 등급을 참조하는 모든 테이블의 부모."),
    "tb_evaluation_factors": ("A", "평가 요건", "등급 판정 요건. 정본은 3요건 — 비공지성(S)·경제적 유용성(V)·비밀관리성(M)."),
    "tb_level_keywords": ("A", "등급 키워드", "룰 기반 1차 판정에 쓰는 등급별 키워드 사전."),
    "tb_documents": ("B", "문서", "업로드 문서의 메타·추출 텍스트 위치·처리 상태. 청크·분류·라벨·학습셋이 모두 참조하는 중심 허브."),
    "tb_chunks": ("B", "청크", "문서를 512 토큰 단위로 자른 조각. created_at 기준 월별 RANGE 파티션."),
    "tb_document_labels": ("C", "문서 라벨", "문서 1건의 확정 등급 1행. 라벨 주체(사람·LLM·룰)를 함께 기록한다."),
    "tb_document_factor_scores": ("C", "문서 요건 점수", "문서 × 요건(S·V·M) 별 0~2점. 등급은 세 점수의 곱으로 정해진다."),
    "tb_classifications": ("D", "분류 결과", "모델 추론 1회의 결과. 등급·확신도·게이트 판정을 남긴다."),
    "tb_classification_evidence": ("D", "분류 근거", "분류 1건이 어느 청크의 어느 구간을 근거로 삼았는지."),
    "tb_model_versions": ("E", "모델 버전", "학습된 분류기 버전 레지스트리. 활성 버전은 항상 1개."),
    "tb_training_runs": ("E", "학습 실행", "학습 잡 1회의 설정·자원·결과."),
    "tb_training_epochs": ("E", "학습 에폭", "학습 실행 안의 에폭별 손실·지표."),
    "tb_training_datasets": ("E", "학습 데이터셋", "학습 실행이 어느 문서를 train/val/test 중 무엇으로 썼는지."),
    "tb_corrections": ("F", "보정", "검수자의 확정·교정 기록. 재학습에 반영된 행만 소비 표시가 붙는다."),
    "tb_prompt_versions": ("G", "프롬프트 버전", "합성 문서 생성에 쓴 프롬프트 템플릿 버전."),
    "tb_sample_documents": ("G", "합성 문서", "LLM 이 생성한 학습용 문서와 그 검수 상태."),
    "tb_llm_usage": ("H", "LLM 사용량", "LLM 호출별 토큰·비용·지연. called_at 기준 월별 RANGE 파티션."),
    "tb_audit_log": ("H", "감사 로그", "전 API 호출 기록. occurred_at 기준 월별 RANGE 파티션."),
    "tb_guides": ("H", "가이드 버전", "가이드 문서 업로드·색인 버전 이력."),
    "tb_rag_vectors": ("I", "RAG 벡터", "RAG 검색용 임베딩·어휘 색인. dense(HNSW 코사인) + bigram tsvector 하이브리드."),
    "tb_rag_aliases": ("I", "RAG 별칭", "논리 이름 → 물리 컬렉션 매핑. 무중단 재색인 blue/green 스왑."),
}

# 여러 테이블에 같은 뜻으로 나오는 컬럼 — 테이블별 설명이 없을 때만 쓴다.
COMMON = {
    "created_at": "생성 시각",
    "updated_at": "수정 시각",
    "created_by": "생성자 ID",
    "is_active": "활성 여부. FALSE 는 삭제가 아니라 이력 보존",
    "description": "설명(자유 서술)",
}

COLS = {
    "tb_classification_levels": {
        "level_id": "등급 PK",
        "level_code": "등급 코드 — TS · S1 · S2 · S3",
        "level_name": "등급 표시명",
        "level_order": "정렬 순서. 숫자가 작을수록 상위 등급",
        "description": "등급 정의 문구",
        "color_hex": "화면 표시색",
        "loss_weight": "학습 손실 가중치. 상위 등급 미탐에 더 큰 벌점을 주기 위한 값",
        "is_active": "활성 여부. FALSE 는 삭제가 아니라 이력 보존",
    },
    "tb_evaluation_factors": {
        "factor_id": "요건 PK",
        "factor_code": "요건 코드 — 정본 SECRECY · VALUE · MANAGEMENT. 레거시 4요소는 is_active=FALSE 로 보존",
        "factor_name": "요건명 — 비공지성(S) · 경제적 유용성(V) · 비밀관리성(M)",
        "description": "요건 정의 문구",
        "weight": "미사용. 등급은 가중합이 아니라 S×V×M 곱으로 정한다. 하위호환 기본 1.0",
        "is_active": "정본 3요건 TRUE · 레거시 4요소 FALSE",
    },
    "tb_level_keywords": {
        "keyword_id": "키워드 PK",
        "level_id": "이 키워드가 가리키는 등급",
        "keyword": "키워드 문자열",
        "pattern_type": "매칭 방식 — exact · regex 등",
        "factor_id": "이 키워드가 근거로 삼는 요건. NULL 이면 요건 무관",
        "weight": "키워드 가중치",
        "source": "출처 — manual(사람 등록) · seed(초기 시드) 등",
        "example_context": "이 키워드가 실제로 쓰인 예시 문장",
        "is_active": "활성 여부. FALSE 면 사전에서 빼되 이력은 남긴다",
    },
    "tb_documents": {
        "doc_id": "문서 PK",
        "external_ref": "외부 시스템(KL 포털·EDMS) 원천 문서 키. 연동 조인 키",
        "filename": "원본 파일명",
        "source_format": "원본 포맷 — hwp · hwpx · pdf · docx · xlsx · txt 등",
        "file_size_bytes": "원본 파일 크기(바이트)",
        "file_hash": "원본 SHA-256. 같은 파일 재업로드 판별",
        "metadata": "문서 속성 JSON. 출처(source_type)·보안표시·접근범위 등 등급 판정 입력이 여기 들어간다",
        "raw_text_uri": "추출 원문 텍스트 저장 위치",
        "normalized_text_uri": "정규화 텍스트 저장 위치",
        "text_preview": "본문 앞부분 미리보기(최대 2,000자)",
        "char_count": "추출 본문 글자 수",
        "extraction_method": "추출 경로 — parser(전자문서 파싱) · ocr",
        "extraction_quality": "추출 품질 점수(0~1)",
        "ocr_used": "OCR 사용 여부",
        "processing_status": "처리 상태 — pending · processing · done · failed",
        "error_message": "처리 실패 사유",
        "uploaded_at": "업로드 시각",
        "processed_at": "처리 완료 시각",
        "created_by": "업로드 주체 ID",
        "deleted_at": "논리 삭제 시각. NULL 이면 활성이며 조회는 NULL 행만 노출한다",
    },
    "tb_chunks": {
        "chunk_id": "청크 PK(파티션 키와 복합)",
        "doc_id": "원문 문서. 파티션 테이블이라 FK 제약은 걸지 않고 애플리케이션이 정합을 보증한다",
        "chunk_index": "문서 내 청크 순번(0-base)",
        "content": "청크 본문",
        "token_count": "토큰 수(최대 512)",
        "char_count": "글자 수",
        "page_start": "원문 시작 페이지",
        "page_end": "원문 끝 페이지",
        "section_path": "계층 섹션 경로 — 예: {3장, 3.1절}",
        "overlap_prev": "앞 청크와 겹친 토큰 수(기본 64)",
        "overlap_next": "뒤 청크와 겹친 토큰 수(기본 64)",
        "created_at": "생성 시각. 월별 RANGE 파티션 키",
    },
    "tb_document_labels": {
        "doc_id": "대상 문서(PK)",
        "level_id": "확정 등급",
        "labeled_by": "라벨 주체 — human · llm · rule",
        "labeler_id": "라벨 작성자 계정 ID",
        "confidence": "라벨 확신도(0~1)",
        "total_score": "요건 점수 합계",
        "notes": "라벨 메모",
        "is_verified": "검증(서명) 완료 여부",
        "verified_by": "검증자 계정 ID",
        "labeled_at": "라벨 시각",
        "verified_at": "검증 시각",
    },
    "tb_document_factor_scores": {
        "doc_id": "대상 문서(복합 PK)",
        "factor_id": "평가 요건(복합 PK)",
        "score": "요건 점수 0·1·2. DB CHECK 제약 ck_dfs_score_0_2 로 범위를 강제한다",
    },
    "tb_classifications": {
        "classification_id": "분류 PK",
        "doc_id": "대상 문서",
        "model_version": "판정에 쓴 모델 버전 라벨",
        "predicted_level_id": "예측 등급",
        "confidence": "예측 확신도(0~1). 온도 보정 후 값",
        "alternatives": "차순위 등급과 점수 JSON 배열",
        "automation_assessment": "자동확정 게이트가 결정 시점에 본 신호 스냅샷 JSON. 이 컬럼 도입 전 행은 NULL",
        "aggregation_method": "청크 결과 합산 방식 — hybrid 등",
        "chunk_count": "판정에 사용한 청크 수",
        "rag_used": "RAG 근거 사용 여부",
        "rag_top_k": "RAG 조회 상위 K",
        "rag_agreement": "RAG 근거가 모델 예측과 일치했는지",
        "status": "현재 상태 — staging · confirmed · needs_review. 검수·보정이 이후에 바꾼다",
        "initial_status": "게이트의 최초 판정을 생성 시점에 동결한 값. 이후 검수·보정이 건드리지 않는다. 도입 전 행은 NULL",
        "inference_ms": "추론 소요 시간(밀리초)",
        "classified_at": "분류 시각",
    },
    "tb_classification_evidence": {
        "evidence_id": "근거 PK",
        "classification_id": "대상 분류",
        "chunk_id": "근거가 된 청크",
        "evidence_type": "근거 종류 — keyword · attention · rag 등",
        "factor_id": "이 근거가 뒷받침하는 요건. NULL 이면 요건 무관",
        "excerpt": "근거 발췌 원문",
        "excerpt_start": "발췌 시작 위치(청크 내 문자 오프셋)",
        "excerpt_end": "발췌 끝 위치",
        "contribution": "이 근거의 기여도",
        "attention_scores": "토큰별 어텐션 점수 JSON",
        "rag_ref_doc_id": "RAG 근거로 인용한 문서",
        "rag_similarity": "RAG 유사도",
    },
    "tb_model_versions": {
        "version_id": "모델 버전 PK",
        "version_label": "버전 라벨 — v-fe4b386b 형식(학습 산출물 해시)",
        "base_model": "기반 사전학습 모델 이름",
        "model_type": "모델 종류 — classifier · reranker",
        "trained_at": "학습 완료 시각",
        "training_run_id": "이 모델을 만든 학습 실행 ID",
        "training_data_count": "학습 샘플 수",
        "metrics": "최종 지표 JSON — F1 · FNR · Recall 등",
        "model_uri": "모델 저장 경로. 핫리로드가 이 경로로 재구성한다",
        "model_size_mb": "모델 크기(MB)",
        "mlflow_run_id": "MLflow 실험 추적 ID",
        "is_active": "활성 여부. 부분 UNIQUE 인덱스로 활성 1개만 허용한다",
        "activated_at": "활성화 시각",
        "deactivated_at": "비활성화 시각",
        "rolled_back_from": "자동 롤백 출처 버전(자기 참조)",
        "rollback_reason": "롤백 사유",
        "level_snapshot": "학습 시점 등급체계 스냅샷 JSON",
    },
    "tb_training_runs": {
        "run_id": "학습 실행 PK",
        "model_version": "이 실행이 만든 모델 버전",
        "mlflow_run_id": "MLflow 실험 추적 ID",
        "status": "실행 상태 — queued · running · done · failed",
        "started_at": "시작 시각",
        "completed_at": "종료 시각",
        "duration_sec": "소요 초",
        "total_samples": "전체 샘플 수",
        "train_count": "학습 분할 건수",
        "val_count": "검증 분할 건수",
        "test_count": "시험 분할 건수",
        "split_method": "분할 방식 — stratified 등",
        "split_seed": "분할 난수 시드. 재현에 필요하다",
        "hyperparameters": "하이퍼파라미터 JSON — epochs · lr · batch_size 등",
        "gpu_info": "GPU 모델·VRAM·CUDA 버전 JSON",
        "final_metrics": "최종 지표 JSON. 배포 게이트 판정도 이 안에 들어간다",
        "trigger_type": "기동 방식 — manual · scheduled · active_learning",
        "trigger_ref": "기동 근거 식별자",
        "error_message": "실패 사유. 학습 잡 조회 API 가 이 값을 그대로 내보낸다",
        "created_by": "요청자 ID",
    },
    "tb_training_epochs": {
        "run_id": "대상 학습 실행(복합 PK)",
        "epoch": "에폭 번호(복합 PK)",
        "train_loss": "학습 손실",
        "val_loss": "검증 손실",
        "val_metrics": "에폭별 검증 지표 JSON",
        "learning_rate": "스케줄러 적용 후 실제 학습률",
        "logged_at": "기록 시각",
    },
    "tb_training_datasets": {
        "id": "행 PK",
        "run_id": "대상 학습 실행",
        "doc_id": "학습에 쓴 문서",
        "split_type": "분할 구분 — train · val · test",
        "level_id": "학습 시점 라벨 등급",
    },
    "tb_corrections": {
        "correction_id": "보정 PK",
        "classification_id": "대상 분류",
        "original_level_id": "AI 예측 등급",
        "corrected_level_id": "검수자 확정 등급. 확정만 하고 고치지 않았으면 예측 등급과 같다",
        "direction": "보정 방향 — underclass(미탐 보정) · overclass(과분류 보정) · lateral(동위 변경) · confirm(확정)",
        "reason": "보정 사유",
        "corrected_by": "검수자 계정 ID",
        "corrected_at": "보정 시각",
        "consumed_in_run": "이 보정을 반영한 재학습 실행. NULL 이면 미반영",
        "consumed_at": "재학습 반영 시각",
    },
    "tb_prompt_versions": {
        "prompt_version": "프롬프트 버전 PK",
        "chain_stage": "생성 단계 — outline · body · qc",
        "template": "프롬프트 템플릿 원문",
        "avg_quality_score": "이 버전으로 만든 문서의 평균 품질 점수",
        "usage_count": "사용 횟수",
        "approval_rate": "검수 승인 비율",
        "created_by": "등록자 ID",
        "notes": "메모",
    },
    "tb_sample_documents": {
        "sample_id": "합성 문서 PK",
        "doc_id": "문서 테이블에 적재됐을 때의 문서 ID. 미적재면 NULL",
        "target_level_id": "생성 때 요구한 등급",
        "corrected_level_id": "검수자가 고친 등급. NULL 이면 교정 없음. 학습행 라벨은 이 값을 우선한다",
        "doc_type": "문서 종류",
        "outline_prompt_version": "개요 생성에 쓴 프롬프트 버전",
        "body_prompt_version": "본문 생성에 쓴 프롬프트 버전",
        "qc_prompt_version": "품질검사에 쓴 프롬프트 버전",
        "llm_provider": "생성 LLM 제공자",
        "llm_model": "생성 LLM 모델명",
        "generated_outline": "생성된 개요",
        "generated_content": "생성된 본문",
        "quality_score": "품질 점수",
        "quality_report": "품질검사 상세 JSON",
        "label_source": "본문 출처 마커 — NULL(정상 생성) · noop_fallback(자리표시 본문·학습 편입 금지) · llm_nonjson(비-JSON 응답)",
        "parse_error": "생성 응답 파싱 실패 사유",
        "review_status": "검수 상태 — pending_review · approved · rejected",
        "reviewed_by": "검수자 계정 ID",
        "reviewed_at": "검수 시각",
        "rejection_reason": "반려 사유",
    },
    "tb_llm_usage": {
        "usage_id": "사용 기록 PK(파티션 키와 복합)",
        "provider": "LLM 제공자",
        "model": "모델명",
        "purpose": "호출 목적 — 합성 · 라벨링 · 질의응답 등",
        "reference_type": "연관 대상 종류",
        "reference_id": "연관 대상 식별자",
        "input_tokens": "입력 토큰 수",
        "output_tokens": "출력 토큰 수",
        "cost_usd": "비용(USD)",
        "cost_krw": "비용(KRW)",
        "billing_phase": "과금 구분 — development · operation",
        "latency_ms": "응답 지연(밀리초)",
        "success": "호출 성공 여부",
        "error_code": "실패 코드",
        "called_at": "호출 시각. 월별 RANGE 파티션 키",
    },
    "tb_audit_log": {
        "audit_id": "감사 PK(파티션 키와 복합)",
        "request_id": "요청 추적 ID. 같은 요청에서 나온 여러 기록을 잇는다",
        "actor_id": "행위자 계정 ID",
        "actor_role": "행위자 역할",
        "action": "수행한 동작",
        "target_type": "대상 종류",
        "target_id": "대상 식별자",
        "payload_hash": "요청 본문 SHA-256. 본문 원문은 남기지 않고 해시만 남긴다",
        "ip_address": "요청 IP(INET 타입)",
        "user_agent": "요청 User-Agent",
        "success": "처리 성공 여부",
        "error_code": "실패 코드",
        "occurred_at": "발생 시각. 월별 RANGE 파티션 키",
    },
    "tb_guides": {
        "id": "행 PK",
        "guide_id": "가이드 논리 ID",
        "version": "가이드 버전. (guide_id, version) 전역 UNIQUE",
        "effective_date": "시행일",
        "change_summary": "변경 요약",
        "doc_type": "문서 종류",
        "filename": "원본 파일명",
        "indexed": "색인 완료 여부",
        "embedding_vector_count": "색인된 벡터 수",
        "index_name": "물리 색인 이름",
        "alias": "색인 별칭",
        "model": "색인에 쓴 임베딩 모델",
        "registered_at": "등록 시각",
    },
}
