"""AI 솔루션 DB 표준 명명 — 옛 물리명 ↔ KOIPA 표준 물리명 ↔ 논리명(한글) 대응표.

왜 있는가(2026-09-11). 감리 DB 영역 지적(인쇄 71쪽 (다))은 「데이터베이스설계서(AI 솔루션)」의
표준 준수 미흡이다. 설계서의 물리명은 실제 DB 와 같아야 하므로 실제 DB 이름을
`KOIPA_AP_표준용어집(용어_단어_도메인_코드)_v1.1` 을 따르는 이름으로 바꿨다
(migration 7b3e9d2a4f10). 이 파일이 그 대응의 정본이다.

출처:
  - 19개 표 · 217개 칼럼 = `KOIPA_DP_데이터베이스 설계서(AI 솔루션)_v1.1` 의 이름 그대로.
    v1.1 의 칼럼ID 193개는 전부 표준단어 약어로만 되어 있고 논리명도 전부 표준용어에 있다(실측).
  - v1.1 에 없던 것 — 새로 지었다. 쓴 단어는 전부 표준단어에 있다:
      tad_dm_doc_vctr_mng · tad_sm_syn_datst_cpst_mng · tad_sy_lck_mng 세 표,
      tad_mm_mdl_ver_mng.actvtn_key · tad_lm_llm_usqty_mng.whol_tkn_cnt(DB 생성 칼럼).
    본문해시내용·잠금명·데이터셋버전명·합성작업아이디·활성키·전체토큰수 는 표준용어로는
    미등록이라 용어집에 자체표준 용어로 올려야 한다.
  - v1.1 을 고친 것 — tad_mm_mdl_ver_mng.mlflow_run_id 를 v1.1 은 EXCN_ID 로 적었으나
    EXCN_ID 는 다른 세 표에서 학습실행 run_id 다. 학습실행 표의 같은 값(FLW_EXCN_ID)에 맞췄다.
  - 영역 코드 sy(시스템)는 새로 둔 것이다. 접두 규칙은 설계서·용어집 어디에도 적혀 있지 않고,
    기존 이름의 "영역 첫 글자 + m" 으로는 잠금 표에 맞는 자리가 없었다(s·c·l 모두 사용 중).

⚠ 이름만 표준을 따른다. 형식(타입)은 현행 그대로다 — v1.1 의 형식을 따르면 0~1 점수가
  DECIMAL(7,0)(정수)로, 밀리초가 CHAR(6)(시분초 문자)로 바뀌어 값이 깨진다(13칼럼 실측).
⚠ 인덱스·제약·시퀀스 이름(idx_* · *_pkey 등)은 바꾸지 않았다. 표준용어집 적용 대상이 아니다.
"""

from __future__ import annotations

# 옛 표 이름 → (표준 표 이름, 논리명)
TABLES: dict[str, tuple[str, str]] = {
    "tb_audit_log": ("tad_am_adt_log_mng", "감사로그관리"),
    "tb_chunks": ("tad_cm_chnk_mng", "청크관리"),
    "tb_classification_evidence": ("tad_cm_clsf_bss_mng", "분류근거관리"),
    "tb_classification_levels": ("tad_cm_clsf_grd_mng", "분류등급관리"),
    "tb_classifications": ("tad_cm_clsf_rslt_mng", "분류결과관리"),
    "tb_corrections": ("tad_cm_crct_mng", "보정관리"),
    "tb_document_factor_scores": ("tad_dm_doc_rqmt_scr_mng", "문서요건점수관리"),
    "tb_document_labels": ("tad_dm_doc_lbl_mng", "문서라벨관리"),
    "tb_documents": ("tad_dm_doc_mng", "문서관리"),
    "tb_evaluation_factors": ("tad_em_evl_rqmt_mng", "평가요건관리"),
    "tb_level_keywords": ("tad_gm_grd_kywd_mng", "등급키워드관리"),
    "tb_guides": ("tad_gm_guide_ver_mng", "가이드버전관리"),
    "tb_llm_usage": ("tad_lm_llm_usqty_mng", "LLM사용량관리"),
    "tb_training_datasets": ("tad_lm_lrn_datst_mng", "학습데이터셋관리"),
    "tb_training_epochs": ("tad_lm_lrn_epoch_mng", "학습에폭관리"),
    "tb_training_runs": ("tad_lm_lrn_excn_mng", "학습실행관리"),
    "tb_model_versions": ("tad_mm_mdl_ver_mng", "모델버전관리"),
    "tb_prompt_versions": ("tad_pm_prmpt_ver_mng", "프롬프트버전관리"),
    "tb_sample_documents": ("tad_sm_syn_doc_mng", "합성문서관리"),
    "tb_document_vectors": ("tad_dm_doc_vctr_mng", "문서벡터관리"),
    "tb_sample_dataset_membership": ("tad_sm_syn_datst_cpst_mng", "합성데이터셋구성관리"),
    "tb_advisory_locks": ("tad_sy_lck_mng", "잠금관리"),
}

# 옛 표 이름 → ((옛 칼럼, 표준 칼럼, 논리명), ...) — 칼럼 순서는 DB 순서.
# 옛 이름과 표준 이름이 같은 칼럼(doc_id 등)도 논리명 때문에 싣는다.
COLUMNS: dict[str, tuple[tuple[str, str, str], ...]] = {
    "tb_audit_log": (
        ("audit_id", "adt_sn", "감사일련번호"),
        ("request_id", "dmnd_id", "요청아이디"),
        ("actor_id", "actr_id", "행위자아이디"),
        ("actor_role", "actr_role_nm", "행위자역할명"),
        ("action", "flfmt_bhvr_cd", "수행동작코드"),
        ("target_type", "trgt_type_cd", "대상유형코드"),
        ("target_id", "trgt_id", "대상아이디"),
        ("payload_hash", "dmnd_mtxt_hash_cn", "요청본문해시내용"),
        ("ip_address", "dmnd_ip_addr", "요청IP주소"),
        ("user_agent", "user_agnt_cn", "사용자에이전트내용"),
        ("success", "scs_yn", "성공여부"),
        ("error_code", "err_cd", "오류코드"),
        ("occurred_at", "ocrn_dt", "발생일시"),
    ),
    "tb_chunks": (
        ("chunk_id", "chnk_id", "청크아이디"),
        ("doc_id", "doc_id", "문서아이디"),
        ("chunk_index", "chnk_no", "청크번호"),
        ("content", "chnk_cn", "청크내용"),
        ("token_count", "tkn_cnt", "토큰수"),
        ("char_count", "char_cnt", "글자수"),
        ("section_path", "sctn_path_nm", "구간경로명"),
        ("overlap_prev", "prev_chnk_ovlp_tkn_cnt", "앞청크중첩토큰수"),
        ("overlap_next", "next_chnk_ovlp_tkn_cnt", "뒤청크중첩토큰수"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_classification_evidence": (
        ("evidence_id", "bss_sn", "근거일련번호"),
        ("classification_id", "clsf_id", "분류아이디"),
        ("chunk_id", "chnk_id", "청크아이디"),
        ("evidence_type", "bss_type_nm", "근거유형명"),
        ("factor_id", "rqmt_sn", "요건일련번호"),
        ("excerpt", "exct_cn", "발췌내용"),
        ("excerpt_start", "exct_bgng_pstn_nm", "발췌시작위치명"),
        ("excerpt_end", "exct_end_pstn_nm", "발췌종료위치명"),
        ("contribution", "cndg_nvl", "기여도수치"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_classification_levels": (
        ("level_id", "grd_sn", "등급일련번호"),
        ("level_code", "grd_cd", "등급코드"),
        ("level_name", "grd_nm", "등급명"),
        ("level_order", "grd_seq", "등급순서"),
        ("description", "clsf_grd_expln", "분류등급설명"),
        ("color_hex", "colr_cd", "색상코드"),
        ("loss_weight", "loss_wgvl_cfc", "손실가중치계수"),
        ("is_active", "actvtn_yn", "활성여부"),
        ("created_at", "crt_dt", "생성일시"),
        ("updated_at", "mdfcn_dt", "수정일시"),
        ("created_by", "creatr_id", "생성자아이디"),
    ),
    "tb_classifications": (
        ("classification_id", "clsf_id", "분류아이디"),
        ("doc_id", "doc_id", "문서아이디"),
        ("model_version", "mdl_ver_nm", "모델버전명"),
        ("predicted_level_id", "predc_grd_sn", "예측등급일련번호"),
        ("confidence", "rlbl_scr", "신뢰점수"),
        ("alternatives", "nxtrnk_grd_list_cn", "차순위등급목록내용"),
        ("automation_assessment", "auto_cfmtn_evl_info_cn", "자동확정평가정보내용"),
        ("aggregation_method", "tot_mth_cd", "집계방식코드"),
        ("chunk_count", "chnk_cnt", "청크수"),
        ("status", "clsf_stts_nm", "분류상태명"),
        ("initial_status", "clsf_frst_stts_nm", "분류최초상태명"),
        ("inference_ms", "infr_req_hr", "추론소요시간"),
        ("classified_at", "clsf_dt", "분류일시"),
    ),
    "tb_corrections": (
        ("correction_id", "crct_sn", "보정일련번호"),
        ("classification_id", "clsf_id", "분류아이디"),
        ("original_level_id", "orgnl_grd_sn", "원본등급일련번호"),
        ("corrected_level_id", "cfmtn_grd_sn", "확정등급일련번호"),
        ("direction", "crct_ornt_nm", "보정방향명"),
        ("reason", "crct_rsn", "보정사유"),
        ("corrected_by", "clbtr_id", "보정자아이디"),
        ("corrected_at", "crct_dt", "보정일시"),
        ("consumed_in_run", "rflt_lrn_excn_id", "반영학습실행아이디"),
        ("consumed_at", "rflt_dt", "반영일시"),
    ),
    "tb_document_factor_scores": (
        ("doc_id", "doc_id", "문서아이디"),
        ("factor_id", "rqmt_sn", "요건일련번호"),
        ("score", "scr", "점수"),
    ),
    "tb_document_labels": (
        ("doc_id", "doc_id", "문서아이디"),
        ("level_id", "grd_sn", "등급일련번호"),
        ("labeled_by", "lbl_mnbd_nm", "라벨주체명"),
        ("labeler_id", "lbl_wrtr_id", "라벨작성자아이디"),
        ("confidence", "rlbl_scr", "신뢰점수"),
        ("total_score", "tot_scr", "집계점수"),
        ("notes", "memo_dtl_cn", "메모상세내용"),
        ("is_verified", "vrfc_cmptn_yn", "검증완료여부"),
        ("verified_by", "vrfr_id", "검증자아이디"),
        ("labeled_at", "lbl_dt", "라벨일시"),
        ("verified_at", "vrfc_dt", "검증일시"),
    ),
    "tb_documents": (
        ("doc_id", "doc_id", "문서아이디"),
        ("external_ref", "otsd_rfrnc_no", "외부참조번호"),
        ("filename", "file_nm", "파일명"),
        ("source_format", "orgnl_frmat_nm", "원본포맷명"),
        ("file_size_bytes", "file_sz", "파일크기"),
        ("file_hash", "file_hash_nm", "파일해시명"),
        ("metadata", "mtdt_dsctn", "메타데이터내역"),
        ("raw_text_uri", "orgtxt_path_nm", "원문경로명"),
        ("normalized_text_uri", "nrmlz_txt_path_nm", "정규화텍스트경로명"),
        ("text_preview", "mtxt_prvw_cn", "본문미리보기내용"),
        ("char_count", "char_cnt", "글자수"),
        ("extraction_method", "extr_mth_nm", "추출방식명"),
        ("extraction_quality", "extr_qlty_scr", "추출품질점수"),
        ("ocr_used", "ocr_use_yn", "OCR사용여부"),
        ("processing_status", "prcs_stts_nm", "처리상태명"),
        ("error_message", "err_stts_msg_cn", "오류상태메시지내용"),
        ("uploaded_at", "uld_dt", "업로드일시"),
        ("processed_at", "prcs_cmptn_dt", "처리완료일시"),
        ("created_by", "creatr_id", "생성자아이디"),
        ("deleted_at", "del_dt", "삭제일시"),
    ),
    "tb_evaluation_factors": (
        ("factor_id", "rqmt_sn", "요건일련번호"),
        ("factor_code", "rqmt_cd", "요건코드"),
        ("factor_name", "rqmt_nm", "요건명"),
        ("description", "evl_rqmt_expln", "평가요건설명"),
        ("weight", "wgvl_cfc", "가중치계수"),
        ("is_active", "actvtn_yn", "활성여부"),
        ("created_at", "crt_dt", "생성일시"),
        ("updated_at", "mdfcn_dt", "수정일시"),
    ),
    "tb_level_keywords": (
        ("keyword_id", "kywd_sn", "키워드일련번호"),
        ("level_id", "grd_sn", "등급일련번호"),
        ("keyword", "kywd_nm", "키워드명"),
        ("pattern_type", "ptn_type_nm", "패턴유형명"),
        ("factor_id", "rqmt_sn", "요건일련번호"),
        ("weight", "wgvl_cfc", "가중치계수"),
        ("source", "src_nm", "출처명"),
        ("is_active", "actvtn_yn", "활성여부"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_guides": (
        ("id", "guide_ver_sn", "가이드버전일련번호"),
        ("guide_id", "guide_id", "가이드아이디"),
        ("version", "guide_ver_nm", "가이드버전명"),
        ("effective_date", "enfc_dt", "시행일시"),
        ("change_summary", "chg_smry_cn", "변경요약내용"),
        ("doc_type", "doc_knd_nm", "문서종류명"),
        ("filename", "file_nm", "파일명"),
        ("registered_at", "reg_dt", "등록일시"),
    ),
    "tb_llm_usage": (
        ("usage_id", "use_rcd_sn", "사용기록일련번호"),
        ("provider", "offr_id", "제공자아이디"),
        ("model", "mdl_nm", "모델명"),
        ("purpose", "clot_prps", "호출목적"),
        ("reference_type", "rfrnc_trgt_type_cd", "참조대상유형코드"),
        ("reference_id", "rfrnc_trgt_id", "참조대상아이디"),
        ("input_tokens", "inpt_tkn_cnt", "입력토큰수"),
        ("output_tokens", "otpt_tkn_cnt", "출력토큰수"),
        ("total_tokens", "whol_tkn_cnt", "전체토큰수"),
        ("cost_usd", "usd_cst", "미화비용"),
        ("cost_krw", "kcur_cst", "원화비용"),
        ("billing_phase", "bllng_se_cd", "과금구분코드"),
        ("latency_ms", "rspns_dly_hr", "응답지연시간"),
        ("success", "scs_yn", "성공여부"),
        ("error_code", "err_cd", "오류코드"),
        ("called_at", "clot_dt", "호출일시"),
    ),
    "tb_training_datasets": (
        ("id", "lrn_datst_sn", "학습데이터셋일련번호"),
        ("run_id", "excn_id", "실행아이디"),
        ("doc_id", "doc_id", "문서아이디"),
        ("split_type", "prttn_se_nm", "분할구분명"),
        ("level_id", "grd_sn", "등급일련번호"),
    ),
    "tb_training_epochs": (
        ("run_id", "excn_id", "실행아이디"),
        ("epoch", "epoch_sn", "에폭일련번호"),
        ("train_loss", "lrn_loss_nvl", "학습손실수치"),
        ("val_loss", "vrfc_loss_nvl", "검증손실수치"),
        ("val_metrics", "vrfc_idct_info_cn", "검증지표정보내용"),
        ("learning_rate", "lrnr", "학습률"),
        ("logged_at", "rcd_dt", "기록일시"),
    ),
    "tb_training_runs": (
        ("run_id", "excn_id", "실행아이디"),
        ("model_version_id", "mdl_ver_id", "모델버전아이디"),
        ("mlflow_run_id", "flw_excn_id", "흐름실행아이디"),
        ("status", "lrn_excn_stts_cd", "학습실행상태코드"),
        ("started_at", "bgng_dt", "시작일시"),
        ("completed_at", "end_dt", "종료일시"),
        ("duration_sec", "req_hr", "소요시간"),
        ("total_samples", "whol_sample_cnt", "전체표본수"),
        ("train_count", "lrn_nocs", "학습건수"),
        ("val_count", "vrfc_nocs", "검증건수"),
        ("test_count", "test_nocs", "시험건수"),
        ("split_method", "prttn_mth_cd", "분할방식코드"),
        ("split_seed", "prttn_seed", "분할시드"),
        ("hyperparameters", "hprprm_info_cn", "하이퍼파라미터정보내용"),
        ("final_metrics", "last_idct_info_cn", "최종지표정보내용"),
        ("trigger_type", "boot_mth_cd", "기동방식코드"),
        ("trigger_ref", "boot_bss_idntfr_nm", "기동근거식별자명"),
        ("error_message", "err_stts_msg_cn", "오류상태메시지내용"),
        ("created_at", "crt_dt", "생성일시"),
        ("created_by", "creatr_id", "생성자아이디"),
    ),
    "tb_model_versions": (
        ("version_id", "mdl_ver_id", "모델버전아이디"),
        ("version_label", "ver_lbl_nm", "버전라벨명"),
        ("base_model", "base_mdl_nm", "기반모델명"),
        ("model_type", "mdl_type_nm", "모델유형명"),
        ("trained_at", "lrn_cmptn_dt", "학습완료일시"),
        ("training_run_id", "lrn_excn_id", "학습실행아이디"),
        ("training_data_count", "lrn_data_nocs", "학습자료건수"),
        ("metrics", "idct_info_cn", "지표정보내용"),
        ("model_uri", "mdl_strg_path_nm", "모델저장경로명"),
        ("mlflow_run_id", "flw_excn_id", "흐름실행아이디"),
        ("is_active", "actvtn_yn", "활성여부"),
        ("active_key", "actvtn_key", "활성키"),
        ("activated_at", "vtlz_dt", "활성화일시"),
        ("deactivated_at", "dsbl_dt", "비활성화일시"),
        ("rolled_back_from", "rlbk_src_ver_id", "롤백출처버전아이디"),
        ("rollback_reason", "rlbk_rsn", "롤백사유"),
        ("level_snapshot", "grd_system_hstry_cn", "등급체계이력내용"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_prompt_versions": (
        ("prompt_version", "prmpt_ver_nm", "프롬프트버전명"),
        ("chain_stage", "crt_stp_nm", "생성단계명"),
        ("template", "tmplt_cn", "서식내용"),
        ("created_at", "crt_dt", "생성일시"),
        ("created_by", "creatr_id", "생성자아이디"),
        ("notes", "prmpt_ver_memo_cn", "프롬프트버전메모내용"),
    ),
    "tb_sample_documents": (
        ("sample_id", "syn_doc_id", "합성문서아이디"),
        ("doc_id", "doc_id", "문서아이디"),
        ("target_level_id", "goal_grd_sn", "목표등급일련번호"),
        ("corrected_level_id", "cfmtn_grd_sn", "확정등급일련번호"),
        ("doc_type", "doc_knd_nm", "문서종류명"),
        ("outline_prompt_version", "otln_prmpt_ver_nm", "개요프롬프트버전명"),
        ("body_prompt_version", "mtxt_prmpt_ver_nm", "본문프롬프트버전명"),
        ("qc_prompt_version", "qlty_insp_prmpt_ver_nm", "품질검사프롬프트버전명"),
        ("llm_provider", "llm_offr_nm", "LLM제공자명"),
        ("llm_model", "llm_mdl_nm", "LLM모델명"),
        ("generated_outline", "crt_otln", "생성개요"),
        ("generated_content", "crt_mtxt_cn", "생성본문내용"),
        ("quality_score", "qlty_scr", "품질점수"),
        ("quality_report", "qlty_insp_rptp_cn", "품질검사보고서내용"),
        ("label_source", "lbl_src_nm", "라벨출처명"),
        ("parse_error", "prsng_err_rsn", "파싱오류사유"),
        ("review_status", "igi_stts_cd", "검수상태코드"),
        ("reviewed_by", "chckr_id", "검수자아이디"),
        ("reviewed_at", "igi_dt", "검수일시"),
        ("rejection_reason", "rjct_rsn", "반려사유"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_document_vectors": (
        ("doc_id", "doc_id", "문서아이디"),
        ("embedding", "embd_vctr_cn", "임베딩벡터내용"),
        ("model", "embd_mdl_nm", "임베딩모델명"),
        ("chunk_count", "chnk_cnt", "청크수"),
        ("content_sha256", "mtxt_hash_cn", "본문해시내용"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_sample_dataset_membership": (
        ("membership_id", "cpst_sn", "구성일련번호"),
        ("sample_id", "syn_doc_id", "합성문서아이디"),
        ("dataset_version", "datst_ver_nm", "데이터셋버전명"),
        ("synth_job_id", "syn_job_id", "합성작업아이디"),
        ("created_at", "crt_dt", "생성일시"),
    ),
    "tb_advisory_locks": (
        ("name", "lck_nm", "잠금명"),
    ),
}


def logical_names() -> dict[str, tuple[str, dict[str, str]]]:
    """표준 표 이름 → (표 논리명, {표준 칼럼: 칼럼 논리명}). 정의서·ERD 생성기가 쓴다."""
    return {
        TABLES[old][0]: (TABLES[old][1], {new: ko for _, new, ko in cols})
        for old, cols in COLUMNS.items()
    }
